eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: paymentservice
server:
  port: 9090
spring:
  application:
    name: PAYMENT-SERVICE
  zipkin:
    base-url: http://zipkin:9411/